### ISSUE TITLE
Refactor style-components slightly

### ISSUE THREAD

**Issue by kylewetton** [kylewetton/walnuts#1]
I'd love someone to help refactor styled-components, do whatever you want but keep the styling the same (which is a WIP). Ideas could be adding a theme provider, move bulk of styling to a dedicated js file, just whatever is best practice, looking to learn from someone more experienced than I at SPA. Cheers!

**Comment by flipps** [comment]
Hi kylewetton, I would like to make some suggestions about how to handle styles with styled-components, if it's okay to you. As soon as I finish I'll send you a PR to see if it makes sense to you :).

**Comment by kylewetton** [comment]
Sounds great, do I have to assign you or anything?

**Comment by flipps** [comment]
I guess it's not necessary :)

**Comment by kylewetton** [comment]
If there's anything else about the way the project has been laid out, feel free to tweak it. Theres some things that just didn't work for me.

I've seen people import a file like this

Directory
`./components/ProductPage/index.js`

And the import...
`import ProjectPage from './ProjectPage'`

But I literally have to go
`import ProjectPage from './ProjectPage/ProjectPage'`

I don't know why

**Comment by flipps** [comment]
Cool! I did some changes on the Home components folder and ProductPage folder. I used a different approach for the import/export of components to see if you prefer that way. I will explain with more detail at the PR comments, and then if you want we can discuss it more
